#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Fuwu.Common.Web.Views.Shared.Partials
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
    using Com.Fuwu.Common.Web.Configurations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Partials/Site.Top.Short.cshtml")]
    public partial class Site_Top_Short : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Site_Top_Short()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"mod-toolbar mod-toolbar-mini\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"toolbar dynamic-content\"");

WriteLiteral(" ng-controller=\"UserNavTop\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"tb-logo\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 221), Tuple.Create("\"", 246)
            
            #line 5 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 228), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Www
            
            #line default
            #line hidden
, 228), false)
);

WriteLiteral(" class=\"tb-logo-link\"");

WriteLiteral(" title=\"福务首页\"");

WriteLiteral(">福务网首页</a></p>\r\n            <ul");

WriteLiteral(" class=\"tb-nav\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-nav-index\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 386), Tuple.Create("\"", 411)
            
            #line 7 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 393), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Www
            
            #line default
            #line hidden
, 393), false)
);

WriteLiteral(" title=\"福务网首页\"");

WriteLiteral(">福务网首页</a></li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item toolbar-interval\"");

WriteLiteral("></li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-nav-cate all-categories\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"menu-hd\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ico-cate\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 645), Tuple.Create("\"", 687)
            
            #line 10 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 652), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Www+"/Home/Class/"
            
            #line default
            #line hidden
, 652), false)
);

WriteLiteral(" title=\"\"");

WriteLiteral(">全部福务分类</a><i");

WriteLiteral(" class=\"ico-drop hide\"");

WriteLiteral("></i></div>\r\n                    <div");

WriteLiteral(" class=\"tb-cate-con hide dynamic-content\"");

WriteLiteral(" style=\"left: -236px;display:none!important\"");

WriteLiteral(" ng-controller=\"AllCategories\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"tb-cate-list\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" ng-repeat=\"parent in categories | filter:isRoot\"");

WriteLiteral(" class=\"root-cate\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" href=\"{{\'/Search?ct=\'+parent.CategoryNo}}\"");

WriteLiteral("><h4");

WriteLiteral(" class=\"tb-cate-list-hd\"");

WriteLiteral("><i");

WriteLiteral(" class=\"i01\"");

WriteLiteral("></i><span");

WriteLiteral(" class=\"c693\"");

WriteLiteral(" ng-bind=\"parent.CategoryName\"");

WriteLiteral("></span></h4></a>\r\n                                <div");

WriteLiteral(" ng-repeat=\"child in children(parent)\"");

WriteLiteral(" class=\"parent-cate tb-cate-second\"");

WriteLiteral(">\r\n                                    <h5");

WriteLiteral(" class=\"tb-cate-list-hd\"");

WriteLiteral("><span");

WriteLiteral(" ng-bind=\"child.CategoryName\"");

WriteLiteral("></span></h5>\r\n                                    <p");

WriteLiteral(" class=\"tb-cate-list-bd leaf-cate\"");

WriteLiteral(" ng-show=\"false\"");

WriteLiteral(">\r\n                                        <a");

WriteLiteral(" href=\"{{\'/Search?ct=\'+leaf.CategoryNo}}\"");

WriteLiteral(" ng-repeat=\"leaf in children(child)\"");

WriteLiteral(" ng-bind=\"leaf.CategoryName\"");

WriteLiteral("></a>\r\n                                    </p>\r\n                                " +
"</div>\r\n                            </li>\r\n                        </ul>\r\n      " +
"              </div>\r\n                </li>\r\n            </ul>\r\n            <ul");

WriteLiteral(" class=\"tb-login-info\"");

WriteLiteral(" ng-if=\"!user\"");

WriteLiteral(" ng-cloak>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-search\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"icon-drop\"");

WriteLiteral("></i>\r\n                    <div");

WriteLiteral(" class=\"search-tab search-tri\"");

WriteLiteral(">\r\n                        <ul>\r\n                            <li");

WriteLiteral(" class=\"selected\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" st=\"0\"");

WriteLiteral(">找福务</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" st=\"1\"");

WriteLiteral(">找褔师</a></li>\r\n                        </ul>\r\n                    </div>\r\n       " +
"             <form");

WriteAttribute("action", Tuple.Create(" action=\"", 2400), Tuple.Create("\"", 2441)
            
            #line 35 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 2409), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Www + "/Search"
            
            #line default
            #line hidden
, 2409), false)
);

WriteLiteral(" class=\"search-form\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"app\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"Ord\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"q\"");

WriteLiteral(" class=\"inpt\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"tb-btn-search\"");

WriteLiteral(" />\r\n                    </form>\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-my-center\"");

WriteLiteral("><em>你好，<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2854), Tuple.Create("\"", 2899)
            
            #line 42 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 2861), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/Login"
            
            #line default
            #line hidden
, 2861), false)
);

WriteLiteral(">请登录</a></em></li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-fuwu-center\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"nomarl\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"ico-fw-fuke\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3074), Tuple.Create("\"", 3122)
            
            #line 45 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 3081), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/Register"
            
            #line default
            #line hidden
, 3081), false)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(">成为福客</a>\r\n                    </span>\r\n                </li>\r\n                <l" +
"i");

WriteLiteral(" class=\"toolbar-item tb-fuwu-center\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"nomarl\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"ico-fw-center\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3357), Tuple.Create("\"", 3413)
            
            #line 50 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 3364), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/RegisterProvider"
            
            #line default
            #line hidden
, 3364), false)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(">成为福师</a>\r\n                    </span>\r\n                </li>\r\n            </ul>\r" +
"\n            <ul");

WriteLiteral(" class=\"tb-login-info\"");

WriteLiteral(" ng-if=\"user\"");

WriteLiteral(" ng-cloak>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-search\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"icon-drop\"");

WriteLiteral("></i>\r\n                    <div");

WriteLiteral(" class=\"search-tab search-tri\"");

WriteLiteral(">\r\n                        <ul>\r\n                            <li");

WriteLiteral(" class=\"selected\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" st=\"0\"");

WriteLiteral(">找福务</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" st=\"1\"");

WriteLiteral(">找褔师</a></li>\r\n                        </ul>\r\n                    </div>\r\n       " +
"             <form");

WriteAttribute("action", Tuple.Create(" action=\"", 3991), Tuple.Create("\"", 4032)
            
            #line 63 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 4000), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Www + "/Search"
            
            #line default
            #line hidden
, 4000), false)
);

WriteLiteral(" class=\"search-form\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"app\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"Ord\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"q\"");

WriteLiteral(" class=\"inpt\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"tb-btn-search\"");

WriteLiteral(" />\r\n                    </form>\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-my-center\"");

WriteLiteral("><em>你好，<a");

WriteAttribute("href", Tuple.Create(" href=\"", 4445), Tuple.Create("\"", 4477)
            
            #line 70 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 4452), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 4452), false)
);

WriteLiteral(" class=\"users-name\"");

WriteLiteral(" ng-bind=\"user.NickName\"");

WriteLiteral("></a></em></li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item item-msg2\"");

WriteLiteral(" style=\"z-index:500\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"menu-hd\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ico-email\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4723), Tuple.Create("\"", 4768)
            
            #line 73 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 4730), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 4730), false)
, Tuple.Create(Tuple.Create("", 4755), Tuple.Create("/notice/index", 4755), true)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">消息<i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" style=\"color: #FF4401; font-family: arial; font-weight: bold; margin: 0 6px;\"");

WriteLiteral(" ng-bind=\"user.TotalMessageCount\"");

WriteLiteral(" ng-if=\"user.TotalMessageCount\"");

WriteLiteral("></i></a><i");

WriteLiteral(" class=\"ico-msg\"");

WriteLiteral("></i><i");

WriteLiteral(" class=\"ico-drop\"");

WriteLiteral("></i></div>\r\n                        <div");

WriteLiteral(" class=\"menu-bd\"");

WriteLiteral(">\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5089), Tuple.Create("\"", 5141)
            
            #line 75 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 5096), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 5096), false)
, Tuple.Create(Tuple.Create("", 5121), Tuple.Create("/notice/index?type=2", 5121), true)
);

WriteLiteral(">订单提醒<i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" style=\"color: #FF4401; font-family: arial; font-weight: bold; margin: 0 6px;\"");

WriteLiteral(" ng-bind=\"user.OrderMessageCount\"");

WriteLiteral(" ng-if=\"user.OrderMessageCount\"");

WriteLiteral("></i></a></p>\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5352), Tuple.Create("\"", 5404)
            
            #line 76 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 5359), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 5359), false)
, Tuple.Create(Tuple.Create("", 5384), Tuple.Create("/notice/index?type=1", 5384), true)
);

WriteLiteral(">开课通知<i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" style=\"color: #FF4401; font-family: arial; font-weight: bold; margin: 0 6px;\"");

WriteLiteral(" ng-bind=\"user.CourseMessageCount\"");

WriteLiteral(" ng-if=\"user.CourseMessageCount\"");

WriteLiteral("></i></a></p>\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5617), Tuple.Create("\"", 5669)
            
            #line 77 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 5624), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 5624), false)
, Tuple.Create(Tuple.Create("", 5649), Tuple.Create("/notice/index?type=3", 5649), true)
);

WriteLiteral(">系统通知<i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" style=\"color: #FF4401; font-family: arial; font-weight: bold; margin: 0 6px;\"");

WriteLiteral(" ng-bind=\"user.SystemMessageCount\"");

WriteLiteral(" ng-if=\"user.SystemMessageCount\"");

WriteLiteral("></i></a></p>\r\n                        </div>\r\n                    </div>\r\n      " +
"          </li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-fuwu-center\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"menu-hd\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ico-fw-center\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6106), Tuple.Create("\"", 6151)
            
            #line 83 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
   , Tuple.Create(Tuple.Create("", 6113), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Business
            
            #line default
            #line hidden
, 6113), false)
, Tuple.Create(Tuple.Create("", 6136), Tuple.Create("/ProviderCenter", 6136), true)
);

WriteLiteral(">福师中心</a><i");

WriteLiteral(" class=\"ico-drop\"");

WriteLiteral("></i></div>\r\n                        <div");

WriteLiteral(" class=\"menu-bd\"");

WriteLiteral(">\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6273), Tuple.Create("\"", 6316)
            
            #line 85 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 6280), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Business + "/Order"
            
            #line default
            #line hidden
, 6280), false)
);

WriteLiteral(">我提供的福务</a></p>\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6367), Tuple.Create("\"", 6424)
            
            #line 86 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 6374), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Business + "/CoursePublish/Index"
            
            #line default
            #line hidden
, 6374), false)
);

WriteLiteral(">免费发布</a></p>\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6473), Tuple.Create("\"", 6533)
            
            #line 87 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 6480), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Business + "/CourseManagement/Index"
            
            #line default
            #line hidden
, 6480), false)
);

WriteLiteral(">福务管理</a></p>\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6582), Tuple.Create("\"", 6641)
            
            #line 88 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 6589), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Business + "/ProviderCenter/MyUser"
            
            #line default
            #line hidden
, 6589), false)
);

WriteLiteral(">我的福客</a></p>\r\n                        </div>\r\n                    </div>\r\n      " +
"          </li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-fuwu-center2\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"menu-hd\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ico-fw-fuke\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6913), Tuple.Create("\"", 6945)
            
            #line 94 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
 , Tuple.Create(Tuple.Create("", 6920), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 6920), false)
);

WriteLiteral(">福客中心</a><i");

WriteLiteral(" class=\"ico-drop\"");

WriteLiteral("></i></div>\r\n                        <div");

WriteLiteral(" class=\"menu-bd\"");

WriteLiteral(">\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7067), Tuple.Create("\"", 7121)
            
            #line 96 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 7074), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/MyCourse/Index"
            
            #line default
            #line hidden
, 7074), false)
);

WriteLiteral(">我获得的福务</a></p>\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7172), Tuple.Create("\"", 7228)
            
            #line 97 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 7179), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/MySubscibe/Index"
            
            #line default
            #line hidden
, 7179), false)
);

WriteLiteral(">我的订阅</a></p>\r\n                            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7277), Tuple.Create("\"", 7331)
            
            #line 98 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
, Tuple.Create(Tuple.Create("", 7284), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/Favorite/Index"
            
            #line default
            #line hidden
, 7284), false)
);

WriteLiteral(">我的收藏</a></p>\r\n                        </div>\r\n                    </div>\r\n      " +
"          </li>\r\n                <li");

WriteLiteral(" class=\"toolbar-item tb-loginout\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ico-loginout\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7513), Tuple.Create("\"", 7565)
            
            #line 102 "..\..\Views\Shared\Partials\Site.Top.Short.cshtml"
           , Tuple.Create(Tuple.Create("", 7520), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/Login/LogOff"
            
            #line default
            #line hidden
, 7520), false)
);

WriteLiteral(">退出</a></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
