#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Fuwu.Common.Web.Views.Shared.Partials
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Partials\Site.Goto.cshtml"
    using Com.Fuwu.Common.Web.Configurations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Partials/Site.Goto.cshtml")]
    public partial class Site_Goto : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Site_Goto()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\Partials\Site.Goto.cshtml"
  
    var showRightAside = ViewBag.HideRightAside == null;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\Partials\Site.Goto.cshtml"
 if (showRightAside)
{

            
            #line default
            #line hidden
WriteLiteral("    <ul");

WriteLiteral(" class=\"fixed-aside goto-btns dynamic-content\"");

WriteLiteral(" id=\"J_fixed_aside\"");

WriteLiteral(" ng-controller=\"IMMessages\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"fixed-goTop\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"返回顶部\"");

WriteLiteral(" id=\"J_goTop\"");

WriteLiteral("></a></li>\r\n        <li");

WriteLiteral(" class=\"fixed-research\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 353), Tuple.Create("\"", 385)
            
            #line 9 "..\..\Views\Shared\Partials\Site.Goto.cshtml"
, Tuple.Create(Tuple.Create("", 360), Tuple.Create<System.Object, System.Int32>(Hosts.Default.HelpCenter
            
            #line default
            #line hidden
, 360), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" title=\"反馈\"");

WriteLiteral("></a></li>\r\n        <li");

WriteLiteral(" class=\"fixed-cart\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 458), Tuple.Create("\"", 496)
            
            #line 10 "..\..\Views\Shared\Partials\Site.Goto.cshtml"
, Tuple.Create(Tuple.Create("", 465), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 465), false)
, Tuple.Create(Tuple.Create("", 490), Tuple.Create("/Order", 490), true)
);

WriteLiteral(" title=\"我的订单\"");

WriteLiteral("></a></li>\r\n        <li");

WriteLiteral(" class=\"fixed-im\"");

WriteLiteral(" ng-class=\"{\'fixed-im-num\':UnReadIMMMsgCount>0}\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(startIM(\'DoLivimMe\', null))\"");

WriteLiteral(" title=\"IM消息\"");

WriteLiteral("><i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" ng-bind=\"UnReadIMMMsgCount\"");

WriteLiteral(">0</i></a></li>\r\n    </ul>\r\n");

            
            #line 13 "..\..\Views\Shared\Partials\Site.Goto.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
