#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Fuwu.Common.Web.Views.Shared.Partials
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Partials\Site.Top.cshtml"
    using Com.Fuwu.Common.Web.Configurations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Partials/Site.Top.cshtml")]
    public partial class Site_Top : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Site_Top()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\Partials\Site.Top.cshtml"
  
    var hideReturnHomeLink = ViewBag.HideReturnHomeLink != null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"mod-toolbar main-top\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"toolbar dynamic-content\"");

WriteLiteral(" ng-controller=\"UserNavTop\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"toolbar-nomarl ng-cloak\"");

WriteLiteral(" ng-if=\"!user && userDone\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Views\Shared\Partials\Site.Top.cshtml"
            
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\Partials\Site.Top.cshtml"
             if (!hideReturnHomeLink)
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 367), Tuple.Create("\"", 392)
            
            #line 10 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 374), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Www
            
            #line default
            #line hidden
, 374), false)
);

WriteLiteral(" class=\"fuwuHome\"");

WriteLiteral(">福务网首页</a>\r\n");

            
            #line 11 "..\..\Views\Shared\Partials\Site.Top.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <span>你好，</span><a");

WriteAttribute("href", Tuple.Create(" href=\"", 467), Tuple.Create("\"", 512)
            
            #line 12 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 474), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/Login"
            
            #line default
            #line hidden
, 474), false)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(">请登录</a>\r\n        </div>\r\n        <ul");

WriteLiteral(" class=\"toolbar-hd ng-cloak\"");

WriteLiteral(" ng-if=\"user\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\Shared\Partials\Site.Top.cshtml"
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\Partials\Site.Top.cshtml"
             if (!hideReturnHomeLink)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"toolbar-item\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 706), Tuple.Create("\"", 731)
            
            #line 17 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 713), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Www
            
            #line default
            #line hidden
, 713), false)
);

WriteLiteral(" class=\"fuwuHome\"");

WriteLiteral(">福务网首页</a></li>\r\n");

            
            #line 18 "..\..\Views\Shared\Partials\Site.Top.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"toolbar-item login-info\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"menu-hd\"");

WriteLiteral("><span");

WriteLiteral(" class=\"welcome\"");

WriteLiteral(">你好，</span><a");

WriteAttribute("href", Tuple.Create(" href=\"", 902), Tuple.Create("\"", 934)
            
            #line 20 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 909), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 909), false)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(" class=\"users-name\"");

WriteLiteral(" ng-bind=\"user.NickName\"");

WriteLiteral("></a></div>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"toolbar-item item-msg2\"");

WriteLiteral(" style=\"z-index:500;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"menu-hd\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"ico-email\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1225), Tuple.Create("\"", 1270)
            
            #line 25 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 1232), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 1232), false)
, Tuple.Create(Tuple.Create("", 1257), Tuple.Create("/notice/index", 1257), true)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n    消息<i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" style=\"color: #FF4401; font-family: arial; font-weight: bold; margin: 0 6px;\"");

WriteLiteral(" ng-bind=\"user.TotalMessageCount\"");

WriteLiteral(" ng-if=\"user.TotalMessageCount\"");

WriteLiteral(">0</i>\r\n</a><i");

WriteLiteral(" class=\"ico-msg\"");

WriteLiteral("></i><i");

WriteLiteral(" class=\"ico-drop\"");

WriteLiteral("></i>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"menu-bd\"");

WriteLiteral(">\r\n                        <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1629), Tuple.Create("\"", 1681)
            
            #line 30 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 1636), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 1636), false)
, Tuple.Create(Tuple.Create("", 1661), Tuple.Create("/notice/index?type=2", 1661), true)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(">订单提醒<i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" style=\"color: #FF4401; font-family: arial; font-weight: bold; margin: 0 6px;\"");

WriteLiteral(" ng-bind=\"user.OrderMessageCount\"");

WriteLiteral(" ng-if=\"user.OrderMessageCount\"");

WriteLiteral(">0</i></a></p>\r\n                        <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1904), Tuple.Create("\"", 1956)
            
            #line 31 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 1911), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 1911), false)
, Tuple.Create(Tuple.Create("", 1936), Tuple.Create("/notice/index?type=1", 1936), true)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(">开课通知<i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" style=\"color: #FF4401; font-family: arial; font-weight: bold; margin: 0 6px;\"");

WriteLiteral(" ng-bind=\"user.CourseMessageCount\"");

WriteLiteral(" ng-if=\"user.CourseMessageCount\"");

WriteLiteral(">0</i></a></p>\r\n                        <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2181), Tuple.Create("\"", 2233)
            
            #line 32 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 2188), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter
            
            #line default
            #line hidden
, 2188), false)
, Tuple.Create(Tuple.Create("", 2213), Tuple.Create("/notice/index?type=3", 2213), true)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(">系统通知<i");

WriteLiteral(" class=\"numb\"");

WriteLiteral(" style=\"color: #FF4401; font-family: arial; font-weight: bold; margin: 0 6px;\"");

WriteLiteral(" ng-bind=\"user.SystemMessageCount\"");

WriteLiteral(" ng-if=\"user.SystemMessageCount\"");

WriteLiteral(">0</i></a></p>\r\n                    </div>\r\n                </div>\r\n            <" +
"/li>\r\n            <li");

WriteLiteral(" class=\"toolbar-item tb-loginout\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ico-loginout\"");

WriteLiteral("></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2579), Tuple.Create("\"", 2631)
            
            #line 36 "..\..\Views\Shared\Partials\Site.Top.cshtml"
       , Tuple.Create(Tuple.Create("", 2586), Tuple.Create<System.Object, System.Int32>(Hosts.Default.UserCenter + "/Login/LogOff"
            
            #line default
            #line hidden
, 2586), false)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(">退出</a></li>\r\n        </ul>\r\n        <ul");

WriteLiteral(" class=\"toolbar-bd\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"toolbar-item\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"menu-hd\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2810), Tuple.Create("\"", 2835)
            
            #line 40 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 2817), Tuple.Create<System.Object, System.Int32>(Hosts.Default.Www
            
            #line default
            #line hidden
, 2817), false)
);

WriteLiteral(">返回首页</a></div>\r\n            </li>\r\n            ");

WriteLiteral("\r\n            <li");

WriteLiteral(" class=\"toolbar-item item-help\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"menu-hd\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3624), Tuple.Create("\"", 3656)
            
            #line 54 "..\..\Views\Shared\Partials\Site.Top.cshtml"
, Tuple.Create(Tuple.Create("", 3631), Tuple.Create<System.Object, System.Int32>(Hosts.Default.HelpCenter
            
            #line default
            #line hidden
, 3631), false)
);

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">帮助中心</a></div>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"toolbar-item toolbar-interval\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" class=\"toolbar-item item-tel\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ico-tel\"");

WriteLiteral("></i>福务热线 ");

            
            #line 57 "..\..\Views\Shared\Partials\Site.Top.cshtml"
                                                                     Write(Com.Fuwu.Common.Web.Configurations.App.Default.ContactPhone);

            
            #line default
            #line hidden
WriteLiteral(" </li>\r\n        </ul>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
